# Generated by Django 4.1.3 on 2022-11-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('in_use', 'AccountBook in use'), ('deleted', 'AccountBook deleted')], default='in_use', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_books',
            },
        ),
        migrations.CreateModel(
            name='AccountBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_use', 'AccountBookCategory in use'), ('deleted', 'AccountBookCategory deleted')], default='in_use', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_book_categories',
            },
        ),
        migrations.CreateModel(
            name='AccountBookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.CharField(choices=[('expenditure', 'expenditure'), ('income', 'income')], default='expenditure', max_length=200)),
                ('status', models.CharField(choices=[('in_use', 'AccountBookLog in use'), ('deleted', 'AccountBookLog deleted')], default='in_use', max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='account_books.accountbook')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_books.accountbookcategory')),
            ],
            options={
                'db_table': 'account_book_logs',
            },
        ),
    ]
